# Module to Send a Generated Report for the User
import smtplib
from email.mime.text import MIMEText

# Initialise Mail Object
smtpObj = smtplib.SMTP()
# smtpObj.sendmail("")
help(smtpObj)


def send_email_reference():
    # Configuration
    port = 587
    smtp_server = "live.smtp.mailtrap.io"
    login = "api"  # Your login generated by Mailtrap
    password = "1a2b3c4d5e6f7g"  # Your password generated by Mailtrap

    sender_email = "mailtrap@example.com"
    receiver_email = "new@example.com"

    # Plain text content
    text = """\
    Hi,
    Check out the new post on the Mailtrap blog:
    SMTP Server for Testing: Cloud-based or Local?
    https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/
    Feel free to let us know what content would be useful for you!
    """

    # Create MIMEText object
    message = MIMEText(text, "plain")
    message["Subject"] = "Plain text email"
    message["From"] = sender_email
    message["To"] = receiver_email

    # Send the email
    with smtplib.SMTP(smtp_server, port) as server:
        server.starttls()  # Secure the connection
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message.as_string())

    print("Sent")


def send_email(report, spreadsheet):
    print("Its time to send a new report")
